### ISSUE TITLE
写给 egiost 的话

### ISSUE THREAD

**Issue by Carrie999** [Carrie999/blog#12]
既然相遇了，聊过一段时间，我希望分手也能好好的说句话，而不是莫名奇妙的拉黑，人都喜欢找原因，给个不可抗拒原因都是好的

我所理解的你

就是很简单的一个人
喜欢性，喜欢二次元，喜欢二次元的性，喜欢代码，喜欢游戏，喜欢一个人的自在，不大喜欢废话。
很清楚的知道自己喜欢什么，不喜欢什么，似乎不大会关心别人。
你并不是很聪明，但是你很能坚持，每天都去做相同的事情，排除任何其他的干扰。
你很诚实，不会为了某种需求，去欺骗对方。

你能跟我聊天，更多的是想聊一些性的话题。哪天不想聊性了，也就不愿意理我了。

跟你说话，我很谨慎，跟你聊我看过的书，你也没看过，跟你说股票，你也没什么钱又嫉妒。

我不喜欢我爸爸，也不喜欢我哥哥，我害怕男的会打我，害怕男的冷暴力我这是小时候最害怕的事情，是永远的噩梦。

我想我喜欢的并不是你，而是爱情本身。我得到的也是爱情本身的美好。在短短的一个多月的时间里，我真的学会并了解了爱情。

我想我并没有爱过你，因为我没见过你碰过你。

你所有的没有时间做的任何事情，只是因为觉得他不重要，仅此而已。

**Comment by hpan2019github** [comment]
你所有的,没有时间做的,任何事情，只是因为觉得他不重要，仅此而已。
